<a href="https://colab.research.google.com/github/ericb42/GB885-Final-Brauer-E/blob/main/GB885_Final_Brauer_E.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Final Project for GB885 - Python Fundamentals

# RUSH Case Study
RUSH is a globally renowned sportswear and footwear brand.

This notebook is meant to provide analysis of RUSH sales data for use in understanding the market and identifying opportunities for growth.

In [1]:
# install external dependencies

In [2]:
# import modules and packages
import pandas as pd

In [7]:
# load data files
products_url = 'https://raw.githubusercontent.com/ericb42/GB885-Final-Brauer-E/refs/heads/main/data/TABLE_PRODUCTS_885.csv'
retailer_url = 'https://raw.githubusercontent.com/ericb42/GB885-Final-Brauer-E/refs/heads/main/data/TABLE_RETAILER_885.csv'
sales_url = 'https://raw.githubusercontent.com/ericb42/GB885-Final-Brauer-E/refs/heads/main/data/TABLE_SALES_885.csv'

products_df = pd.read_csv(products_url, sep = '|')
retailer_df = pd.read_csv(retailer_url)
sales_df = pd.read_csv(sales_url)

In [8]:
# preview products_df
products_df.head()

   PRODUCT_ID               PRODUCT_NAME
0          20      Men's Street Footwear
1          30    Men's Athletic Footwear
2         120    Women's Street Footwear
3         130  Women's Athletic Footwear
4          40              Men's Apparel

In [9]:
# preview retailer_df
retailer_df.head()

  RETAILER_ID RETAILER     REGION          STATE        CITY
0    A00MOHCO   Amazon    Midwest           Ohio    Columbus
1    A00NMAPO   Amazon  Northeast          Maine    Portland
2    A00NMABO   Amazon  Northeast  Massachusetts      Boston
3    A00NNEMA   Amazon  Northeast  New Hampshire  Manchester
4    A00NVEBU   Amazon  Northeast        Vermont  Burlington

In [10]:
# preview sales_df
sales_df.head()

,ORDER_ID,RETAILER_ID,INVOICE_DATE,MONTH,DAY,YEAR,PRODUCT_ID,PRICE_PER_UNIT,UNITS_SOLD,OPERATING_MARGIN,SALES_METHOD
0,1,A00MOHCO,1/1/2020,1,1,2020,20,50.0,1200,0.5,In-store
1,7,A00MOHCO,1/7/2020,1,7,2020,20,50.0,1250,0.5,In-store
2,13,A00MOHCO,1/25/2020,1,25,2020,20,50.0,1220,0.5,Outlet
3,19,A00MOHCO,1/31/2020,1,31,2020,20,50.0,1200,0.5,Outlet
4,25,A00MOHCO,2/6/2020,2,6,2020,20,60.0,1220,0.5,Outlet